version: "3"
services:
  web:
    container_name: "web"
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/myportfolio
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres
    restart: always
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    image: nginx
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 80
      - 443:443
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

volumes:
  nginx_secrets:
